# Site settings
title: BigNerd.nl
description: Paul Krischer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. https://willianjusten.com.br
url: https://bignerd.nl

# User settings
username: Paul Krischer
user_description: I'm an IT Engineer from the Netherlands. I have a broad skillset with a focus on the open web, performance and security. I work for the <a href=https://openhomefoundation.org>Open Home Foundation</a> and volunteer for <a href=https://hackerhotel.nl/>Hacker Hotel</a>.  
user_title: IT Engineer
email: paul@bignerd.nl
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: krischer
github_username:  sqyd
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
mastodon_url: https://mastodon.social/@SqyD

exclude: ['package.json', 'src', 'node_modules', 'vendor']

